- name: variables in inventary
  hosts: localhost
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, and its duration is {{Duration}}."