- name: variables in inventary
  hosts: localhost
  vars: 
    Timings: "12:00:00"
  tasks: 
  - name: print information
    vars:
      Weeks: "Monday" 
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, and its duration is {{Duration}} timings are {{Timings}} on every {{Weeks}}."