- name: variables from files
  hosts: localhost
  vars_files:
  - vras.yaml
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, and its duration is {{Duration}}."